# Generated by Django 4.1.3 on 2022-11-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totolPrice',
            new_name='totalPrice',
        ),
    ]
